name: Check & Test latest parsers

on:
    push:
        branches:
            - master

jobs:
    check-and-build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository ğŸŒ
                uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.2

            -   name: Set up Java enviroment ğŸ”§
                uses: actions/setup-java@fe779bf55ef683c9413269276a7588bb9cedf07a # v5.2.0
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Set up Gradle enviroment ğŸ“¦
                uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
                with:
                    gradle-version: '9.3.1'

            -   name: Compile the library ğŸš€
                run: ./gradlew compileKotlin
